menu:
- {name: 'Research', url: '/research'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}


social:
- {icon: 'github', style: 'fab', link: 'https://github.com/chengzi-yi'}
- {icon: 'envelope', style: 'fas', link: 'mailto:Chengzi.Yi@nbs.sk'}


contacts:
- {institution: 'National Bank of Slovakia', email: 'Chengzi.Yi[at]nbs.sk', image: 'assets/img/contact.jpg'}
