menu:
- {name: 'Research', url: '/research'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}


social:
- {icon: 'github', style: 'fab', link: 'https://github.com/chengzi-yi'}
- {icon: 'envelope', style: 'fas', link: 'mailto:yic.econ@gmail.com'}


contacts:
- {institution: 'National Bank of Slovakia', email: 'yic.econ[at]gmail.com', image: 'assets/img/contact.jpg'}
